[package]
name = "ipvs"
version = "0.1.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "LGPL-3.0"
description = "Linux IPVS native binding"

[dependencies]
bitflags = "0.9"
byteorder = "1"
libc = "0.2"
